### ISSUE TITLE
[Bug]  Unknown connector runtime exception  in pulsar connector when publishing cloudevents

### ISSUE THREAD

**Issue by fengyongshe** [apache/incubator-eventmesh#1365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

Publish CloudEvents to pulsar connector,   fails with exeception
```
org.apache.eventmesh.api.exception.ConnectorRuntimeException: Unknown connector runtime exception.
        at org.apache.eventmesh.connector.pulsar.producer.AbstractProducer.checkProducerException(AbstractProducer.java:48) ~[?:?]
        at org.apache.eventmesh.connector.pulsar.producer.ProducerImpl.publish(ProducerImpl.java:63) ~[?:?]
        at org.apache.eventmesh.connector.pulsar.producer.PulsarProducerImpl.publish(PulsarProducerImpl.java:44) ~[?:?]
        at org.apache.eventmesh.runtime.core.plugin.MQProducerWrapper.send(MQProducerWrapper.java:81) ~[eventmesh-runtime-1.6.0-release.jar:1.6.0-release]
        at org.apache.eventmesh.runtime.core.protocol.grpc.producer.EventMeshProducer.send(EventMeshProducer.java:46) ~[eventmesh-runtime-1.6.0-release.jar:1.6.0-release]
     ......
```

Causes:
EventMeshExentension only load the dependency jar from ${eventmesh_home}/lib. But Producer in pulsar connector use ProtobufFormat , 
```
    byte[] serializedCloudEvent = EventFormatProvider
                    .getInstance()
                    .resolveFormat(ProtobufFormat.PROTO_CONTENT_TYPE)
                    .serialize(cloudEvent);
```
this is no  cloudevents-protobuf-xx.jar in lib dir。

Resolution：
Add the cloudevents-protobuf dependency in the root build.gradle  or use the jsonFormat as same as other connectors

### How to reproduce

1）Enable pulsar connector by setting connector.plugin.type=pulsar
2)  Send CloudEvent by JAVA SDK
3)  See the eventmesh runtime log, there will be ConnectionRuntimeException
4)  Put the cloudevents-protobuf-xx.jar in the lib dir, can resolve the exception

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by fengyongshe** [comment]
please assign it to  me.
