### ISSUE TITLE
[Bug] configuration file does not exist

### ISSUE THREAD

**Issue by koonchen** [apache/incubator-eventmesh#3053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

I failed to start in standalone mode

### How to reproduce

1. add env properties
```
-Dlog4j.configurationFile=eventmesh-runtime/conf/log4j2.xml
-Deventmesh.log.home=eventmesh-runtime/logs
-Deventmesh.home=eventmesh-runtime
-DconfPath=eventmesh-runtime/conf
```

2. run starter

### Debug logs

```
java.lang.RuntimeException: configuration file does not exist
	at org.apache.eventmesh.common.config.ConfigService.getConfig(ConfigService.java:142) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.common.config.ConfigService.setRootConfig(ConfigService.java:69) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:36) [eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24) [main/:?]
> Task :eventmesh-starter:StartUp.main() FAILED
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
sorry， I can't reproduce your problem， I just use the latest code in master branch, please describe the detail steps thanks.

**Comment by koonchen** [comment]
1. `git@github.com:apache/incubator-eventmesh.git`
2. open with IDEA
3. add vm properties
```
-Dlog4j.configurationFile=eventmesh-runtime/conf/log4j2.xml
-Deventmesh.log.home=eventmesh-runtime/logs
-Deventmesh.home=eventmesh-runtime
-DconfPath=eventmesh-runtime/conf
```
4. run `org.apache.eventmesh.starter.StartUp`
5. error happen:
```
5:52:00 PM: Executing ':eventmesh-starter:StartUp.main()'...


> Configure project :
incubator-eventmesh-1.8.0-release.jar
eventmesh-admin-1.8.0-release.jar
eventmesh-common-1.8.0-release.jar
eventmesh-connector-plugin-1.8.0-release.jar
eventmesh-examples-1.8.0-release.jar
eventmesh-metrics-plugin-1.8.0-release.jar
eventmesh-protocol-plugin-1.8.0-release.jar
eventmesh-registry-plugin-1.8.0-release.jar
eventmesh-runtime-1.8.0-release.jar
eventmesh-sdk-java-1.8.0-release.jar
eventmesh-security-plugin-1.8.0-release.jar
eventmesh-spi-1.8.0-release.jar
eventmesh-starter-1.8.0-release.jar
eventmesh-trace-plugin-1.8.0-release.jar
eventmesh-webhook-1.8.0-release.jar
eventmesh-admin-rocketmq-1.8.0-release.jar
eventmesh-connector-api-1.8.0-release.jar
eventmesh-connector-kafka-1.8.0-release.jar
eventmesh-connector-knative-1.8.0-release.jar
eventmesh-connector-pravega-1.8.0-release.jar
eventmesh-connector-pulsar-1.8.0-release.jar
eventmesh-connector-rabbitmq-1.8.0-release.jar
eventmesh-connector-redis-1.8.0-release.jar
eventmesh-connector-rocketmq-1.8.0-release.jar
eventmesh-connector-standalone-1.8.0-release.jar
eventmesh-metrics-api-1.8.0-release.jar
eventmesh-metrics-prometheus-1.8.0-release.jar
eventmesh-protocol-api-1.8.0-release.jar
eventmesh-protocol-cloudevents-1.8.0-release.jar
eventmesh-protocol-grpc-1.8.0-release.jar
eventmesh-protocol-grpcmessage-1.8.0-release.jar
eventmesh-protocol-http-1.8.0-release.jar
eventmesh-protocol-meshmessage-1.8.0-release.jar
eventmesh-protocol-openmessage-1.8.0-release.jar
eventmesh-protocol-webhook-1.8.0-release.jar
eventmesh-registry-api-1.8.0-release.jar
eventmesh-registry-consul-1.8.0-release.jar
eventmesh-registry-etcd-1.8.0-release.jar
eventmesh-registry-nacos-1.8.0-release.jar
eventmesh-registry-zookeeper-1.8.0-release.jar
eventmesh-security-acl-1.8.0-release.jar
eventmesh-security-api-1.8.0-release.jar
eventmesh-security-auth-http-basic-1.8.0-release.jar
eventmesh-trace-api-1.8.0-release.jar
eventmesh-trace-jaeger-1.8.0-release.jar
eventmesh-trace-pinpoint-1.8.0-release.jar
eventmesh-trace-zipkin-1.8.0-release.jar
eventmesh-webhook-admin-1.8.0-release.jar
eventmesh-webhook-api-1.8.0-release.jar
eventmesh-webhook-receive-1.8.0-release.jar

> Task :eventmesh-common:compileJava UP-TO-DATE
> Task :eventmesh-common:processResources NO-SOURCE
> Task :eventmesh-common:classes UP-TO-DATE
> Task :eventmesh-common:jar UP-TO-DATE
> Task :eventmesh-spi:compileJava UP-TO-DATE
> Task :eventmesh-connector-plugin:eventmesh-connector-api:compileJava UP-TO-DATE
> Task :eventmesh-admin:eventmesh-admin-rocketmq:compileJava UP-TO-DATE
> Task :eventmesh-connector-plugin:eventmesh-connector-standalone:compileJava UP-TO-DATE
> Task :eventmesh-metrics-plugin:eventmesh-metrics-api:compileJava UP-TO-DATE
> Task :eventmesh-metrics-plugin:eventmesh-metrics-prometheus:compileJava UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-api:compileJava UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-cloudevents:compileJava UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-http:compileJava UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-meshmessage:compileJava UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-openmessage:compileJava UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-webhook:compileJava UP-TO-DATE
> Task :eventmesh-registry-plugin:eventmesh-registry-api:compileJava UP-TO-DATE
> Task :eventmesh-registry-plugin:eventmesh-registry-nacos:compileJava UP-TO-DATE
> Task :eventmesh-security-plugin:eventmesh-security-api:compileJava UP-TO-DATE
> Task :eventmesh-security-plugin:eventmesh-security-acl:compileJava UP-TO-DATE
> Task :eventmesh-security-plugin:eventmesh-security-auth-http-basic:compileJava UP-TO-DATE
> Task :eventmesh-trace-plugin:eventmesh-trace-api:compileJava UP-TO-DATE
> Task :eventmesh-trace-plugin:eventmesh-trace-zipkin:compileJava UP-TO-DATE
> Task :eventmesh-webhook:eventmesh-webhook-api:compileJava UP-TO-DATE
> Task :eventmesh-webhook:eventmesh-webhook-admin:compileJava UP-TO-DATE
> Task :eventmesh-webhook:eventmesh-webhook-receive:compileJava UP-TO-DATE
> Task :eventmesh-runtime:compileJava UP-TO-DATE
> Task :eventmesh-runtime:processResources NO-SOURCE
> Task :eventmesh-runtime:classes UP-TO-DATE
> Task :eventmesh-runtime:jar UP-TO-DATE
> Task :eventmesh-spi:processResources NO-SOURCE
> Task :eventmesh-spi:classes UP-TO-DATE
> Task :eventmesh-spi:jar UP-TO-DATE
> Task :eventmesh-connector-plugin:eventmesh-connector-kafka:compileJava
> Task :eventmesh-starter:compileJava
> Task :eventmesh-starter:processResources NO-SOURCE
> Task :eventmesh-starter:classes
> Task :eventmesh-admin:eventmesh-admin-rocketmq:processResources NO-SOURCE
> Task :eventmesh-admin:eventmesh-admin-rocketmq:classes UP-TO-DATE
> Task :eventmesh-admin:eventmesh-admin-rocketmq:jar
> Task :eventmesh-connector-plugin:eventmesh-connector-api:processResources NO-SOURCE
> Task :eventmesh-connector-plugin:eventmesh-connector-api:classes UP-TO-DATE
> Task :eventmesh-connector-plugin:eventmesh-connector-api:jar
> Task :eventmesh-connector-plugin:eventmesh-connector-kafka:processResources
> Task :eventmesh-connector-plugin:eventmesh-connector-kafka:classes
> Task :eventmesh-connector-plugin:eventmesh-connector-kafka:jar
> Task :eventmesh-connector-plugin:eventmesh-connector-standalone:processResources
> Task :eventmesh-connector-plugin:eventmesh-connector-standalone:classes
> Task :eventmesh-connector-plugin:eventmesh-connector-standalone:jar
> Task :eventmesh-metrics-plugin:eventmesh-metrics-api:processResources NO-SOURCE
> Task :eventmesh-metrics-plugin:eventmesh-metrics-api:classes UP-TO-DATE
> Task :eventmesh-metrics-plugin:eventmesh-metrics-api:jar
> Task :eventmesh-metrics-plugin:eventmesh-metrics-prometheus:processResources
> Task :eventmesh-metrics-plugin:eventmesh-metrics-prometheus:classes
> Task :eventmesh-metrics-plugin:eventmesh-metrics-prometheus:jar
> Task :eventmesh-protocol-plugin:eventmesh-protocol-api:processResources NO-SOURCE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-api:classes UP-TO-DATE
> Task :eventmesh-protocol-plugin:eventmesh-protocol-api:jar
> Task :eventmesh-protocol-plugin:eventmesh-protocol-cloudevents:processResources
> Task :eventmesh-protocol-plugin:eventmesh-protocol-cloudevents:classes
> Task :eventmesh-protocol-plugin:eventmesh-protocol-cloudevents:jar
> Task :eventmesh-protocol-plugin:eventmesh-protocol-http:processResources
> Task :eventmesh-protocol-plugin:eventmesh-protocol-http:classes
> Task :eventmesh-protocol-plugin:eventmesh-protocol-http:jar
> Task :eventmesh-protocol-plugin:eventmesh-protocol-meshmessage:processResources
> Task :eventmesh-protocol-plugin:eventmesh-protocol-meshmessage:classes
> Task :eventmesh-protocol-plugin:eventmesh-protocol-meshmessage:jar
> Task :eventmesh-protocol-plugin:eventmesh-protocol-openmessage:processResources
> Task :eventmesh-protocol-plugin:eventmesh-protocol-openmessage:classes
> Task :eventmesh-protocol-plugin:eventmesh-protocol-openmessage:jar
> Task :eventmesh-protocol-plugin:eventmesh-protocol-webhook:processResources
> Task :eventmesh-protocol-plugin:eventmesh-protocol-webhook:classes
> Task :eventmesh-protocol-plugin:eventmesh-protocol-webhook:jar
> Task :eventmesh-registry-plugin:eventmesh-registry-api:processResources NO-SOURCE
> Task :eventmesh-registry-plugin:eventmesh-registry-api:classes UP-TO-DATE
> Task :eventmesh-registry-plugin:eventmesh-registry-api:jar
> Task :eventmesh-registry-plugin:eventmesh-registry-nacos:processResources
> Task :eventmesh-registry-plugin:eventmesh-registry-nacos:classes
> Task :eventmesh-registry-plugin:eventmesh-registry-nacos:jar
> Task :eventmesh-security-plugin:eventmesh-security-acl:processResources
> Task :eventmesh-security-plugin:eventmesh-security-acl:classes
> Task :eventmesh-security-plugin:eventmesh-security-acl:jar
> Task :eventmesh-security-plugin:eventmesh-security-api:processResources NO-SOURCE
> Task :eventmesh-security-plugin:eventmesh-security-api:classes UP-TO-DATE
> Task :eventmesh-security-plugin:eventmesh-security-api:jar
> Task :eventmesh-security-plugin:eventmesh-security-auth-http-basic:processResources
> Task :eventmesh-security-plugin:eventmesh-security-auth-http-basic:classes
> Task :eventmesh-security-plugin:eventmesh-security-auth-http-basic:jar
> Task :eventmesh-trace-plugin:eventmesh-trace-api:processResources
> Task :eventmesh-trace-plugin:eventmesh-trace-api:classes
> Task :eventmesh-trace-plugin:eventmesh-trace-api:jar
> Task :eventmesh-trace-plugin:eventmesh-trace-zipkin:processResources
> Task :eventmesh-trace-plugin:eventmesh-trace-zipkin:classes
> Task :eventmesh-trace-plugin:eventmesh-trace-zipkin:jar
> Task :eventmesh-webhook:eventmesh-webhook-admin:processResources NO-SOURCE
> Task :eventmesh-webhook:eventmesh-webhook-admin:classes UP-TO-DATE
> Task :eventmesh-webhook:eventmesh-webhook-admin:jar
> Task :eventmesh-webhook:eventmesh-webhook-api:processResources NO-SOURCE
> Task :eventmesh-webhook:eventmesh-webhook-api:classes UP-TO-DATE
> Task :eventmesh-webhook:eventmesh-webhook-api:jar
> Task :eventmesh-webhook:eventmesh-webhook-receive:processResources NO-SOURCE
> Task :eventmesh-webhook:eventmesh-webhook-receive:classes UP-TO-DATE
> Task :eventmesh-webhook:eventmesh-webhook-receive:jar

> Task :eventmesh-starter:StartUp.main() FAILED
2023-02-06 17:52:11,936 main ERROR Unable to locate appender "retryAppender" for logger config "retry"
2023-02-06 17:52:12,044 ERROR [main] EventMeshStartup(EventMeshStartup.java:56) - EventMesh start fail.
java.lang.RuntimeException: configuration file does not exist
	at org.apache.eventmesh.common.config.ConfigService.getConfig(ConfigService.java:142) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.common.config.ConfigService.setRootConfig(ConfigService.java:69) ~[eventmesh-common-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:36) [eventmesh-runtime-1.8.0-release.jar:1.8.0-release]
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24) [main/:?]
65 actionable tasks: 38 executed, 27 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':eventmesh-starter:StartUp.main()'.
> Process 'command '/Users/riccochen/Library/Java/JavaVirtualMachines/corretto-1.8.0_312/Contents/Home/bin/java'' finished with non-zero exit value 255

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
5:52:12 PM: Execution finished ':eventmesh-starter:StartUp.main()'.
```
