### ISSUE TITLE
Doc modification 

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#328]
When I start the service according to the [doc](https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/instructions/eventmesh-runtime-quickstart.md)
![image](https://user-images.githubusercontent.com/22415594/117101738-75101a80-ada9-11eb-9030-4cbd3e1632e5.png)
There will throw an exception
```java
java.lang.IllegalStateException: eventMesh.server.env error
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at org.apache.eventmesh.common.config.CommonConfiguration.init(CommonConfiguration.java:68)
	at org.apache.eventmesh.runtime.configuration.EventMeshHTTPConfiguration.init(EventMeshHTTPConfiguration.java:77)
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:40)
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24)
```
It seems the `eventmesh.properties` doesn't been load. I try to modify it to below, this can be solved.
```
-Dlog4j.configurationFile=eventmesh-runtime/conf/log4j2.xml
-Deventmesh.log.home=eventmesh-runtime/logs
-Deventmesh.home=eventmesh-runtime
-DconfPath=eventmesh-runtime/conf
```

**Comment by xwm1992** [comment]
> When I start the service according to the [doc](https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/instructions/eventmesh-runtime-quickstart.md)
> ![image](https://user-images.githubusercontent.com/22415594/117101738-75101a80-ada9-11eb-9030-4cbd3e1632e5.png)
> There will throw an exception
> 
> ```java
> java.lang.IllegalStateException: eventMesh.server.env error
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
> 	at org.apache.eventmesh.common.config.CommonConfiguration.init(CommonConfiguration.java:68)
> 	at org.apache.eventmesh.runtime.configuration.EventMeshHTTPConfiguration.init(EventMeshHTTPConfiguration.java:77)
> 	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:40)
> 	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:24)
> ```
> 
> It seems the `eventmesh.properties` doesn't been load. I try to modify it to below, this can be solved.
> 
> ```
> -Dlog4j.configurationFile=eventmesh-runtime/conf/log4j2.xml
> -Deventmesh.log.home=eventmesh-runtime/logs
> -Deventmesh.home=eventmesh-runtime
> -DconfPath=eventmesh-runtime/conf
> ```

Where did you config this vm configuration for **StartUp Class** or  others?

**Comment by ruanwenjun** [comment]
@xwm1992 `StartUp Class`
