### ISSUE TITLE
MQClientException observed during UNSUBSCRIBE

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#371]
I am using EventMesh with RocketMQ (v4.8.0) as event-store. I am using EventMesh SDK Http LiteConsumer for subscribe / unsubscribe. 

During subscribe process. I observed org.apache.rocketmq.client.exception.MQClientException from EventMesh runtime log.

```
2021-05-21 20:59:59,846 INFO  [eventMesh-clientmanage-2] http(UnSubscribeProcessor.java:66) - cmd=UNSUBSCRIBE|http|client2eventMesh|from=10.213.96.192:47078|to=172.17.0.1
2021-05-21 20:59:59,853 WARN  [eventMesh-clientmanage-2] http(UnSubscribeProcessor.java:138) - client {"consumerGroup":"0c4433303baf4dba966a08f3f3e22949-FT0","dcn":"FT0","env":"P","idc":"FT","ip":"10.213.96.192:47078","lastUpTime":1621630799847,"pid":"300","sys":"0c4433303baf4dba966a08f3f3e22949","topic":"FT0-e-80010001-01-1","url":"http://172.25.0.43:8080/invoke/01F4J41SA3NG8G00GZJ00000AV"} start unsubscribe
2021-05-21 20:59:59,853 INFO  [eventMesh-clientmanage-2] ConsumerManager(ConsumerManager.java:286) - onChange event:consumerGroupStateEvent={consumerGroup=0c4433303baf4dba966a08f3f3e22949-FT0,action=DELETE}
2021-05-21 20:59:59,854 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - [persistAll] Group: ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0 ClientId: 172.17.0.1@0c4433303baf4dba966a08f3f3e22949-FT0-region1(COMMON)-3.0.0-0 updateConsumeOffsetToBroker MessageQueue [topic=%RETRY%ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0, brokerName=broker-a, queueId=0] 0
2021-05-21 20:59:59,854 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - [persistAll] Group: ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0 ClientId: 172.17.0.1@0c4433303baf4dba966a08f3f3e22949-FT0-region1(COMMON)-3.0.0-0 updateConsumeOffsetToBroker MessageQueue [topic=FT0-e-80010001-01-1, brokerName=broker-a, queueId=2] 0
2021-05-21 20:59:59,854 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - [persistAll] Group: ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0 ClientId: 172.17.0.1@0c4433303baf4dba966a08f3f3e22949-FT0-region1(COMMON)-3.0.0-0 updateConsumeOffsetToBroker MessageQueue [topic=FT0-e-80010001-01-1, brokerName=broker-a, queueId=3] 0
2021-05-21 20:59:59,854 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - [persistAll] Group: ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0 ClientId: 172.17.0.1@0c4433303baf4dba966a08f3f3e22949-FT0-region1(COMMON)-3.0.0-0 updateConsumeOffsetToBroker MessageQueue [topic=FT0-e-80010001-01-1, brokerName=broker-a, queueId=0] 0
2021-05-21 20:59:59,854 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - [persistAll] Group: ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0 ClientId: 172.17.0.1@0c4433303baf4dba966a08f3f3e22949-FT0-region1(COMMON)-3.0.0-0 updateConsumeOffsetToBroker MessageQueue [topic=FT0-e-80010001-01-1, brokerName=broker-a, queueId=1] 0
2021-05-21 20:59:59,861 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - unregister client[Producer: null Consumer: ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0] from broker[broker-a 0 10.213.96.192:10911] success
2021-05-21 20:59:59,864 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:100) - unregister client[Producer: CLIENT_INNER_PRODUCER Consumer: null] from broker[broker-a 0 10.213.96.192:10911] success
2021-05-21 20:59:59,864 INFO  [eventMesh-clientmanage-2] RocketmqClient(Slf4jLoggerFactory.java:90) - the producer [CLIENT_INNER_PRODUCER] shutdown OK
2021-05-21 20:59:59,864 INFO  [eventMesh-clientmanage-2] RocketmqCommon(Slf4jLoggerFactory.java:100) - Try to shutdown service thread:PullMessageService started:true lastThread:Thread[PullMessageService,5,main]
2021-05-21 20:59:59,865 INFO  [eventMesh-clientmanage-2] RocketmqCommon(Slf4jLoggerFactory.java:85) - shutdown thread PullMessageService interrupt true
2021-05-21 20:59:59,865 INFO  [PullMessageService] RocketmqClient(Slf4jLoggerFactory.java:85) - PullMessageService service end
2021-05-21 20:59:59,865 INFO  [eventMesh-clientmanage-2] RocketmqCommon(Slf4jLoggerFactory.java:85) - join thread PullMessageService elapsed time(ms) 0 90000
2021-05-21 20:59:59,867 INFO  [eventMesh-clientmanage-2] RocketmqRemoting(Slf4jLoggerFactory.java:95) - closeChannel: begin close the channel[10.213.96.192:10911] Found: true
2021-05-21 20:59:59,867 INFO  [eventMesh-clientmanage-2] RocketmqRemoting(Slf4jLoggerFactory.java:90) - closeChannel: the channel[10.213.96.192:10911] was removed from channel table
2021-05-21 20:59:59,868 INFO  [NettyClientWorkerThread_2] RocketmqRemoting(Slf4jLoggerFactory.java:90) - NETTY CLIENT PIPELINE: CLOSE 10.213.96.192:10911
2021-05-21 20:59:59,869 INFO  [NettyClientWorkerThread_2] RocketmqRemoting(Slf4jLoggerFactory.java:90) - eventCloseChannel: the channel[null] has been removed from the channel table before
2021-05-21 20:59:59,869 INFO  [eventMesh-clientmanage-2] RocketmqRemoting(Slf4jLoggerFactory.java:95) - closeChannel: begin close the channel[10.213.96.192:9876] Found: true
2021-05-21 20:59:59,869 INFO  [eventMesh-clientmanage-2] RocketmqRemoting(Slf4jLoggerFactory.java:90) - closeChannel: the channel[10.213.96.192:9876] was removed from channel table
2021-05-21 20:59:59,869 INFO  [NettyClientWorkerThread_1] RocketmqRemoting(Slf4jLoggerFactory.java:90) - NETTY CLIENT PIPELINE: CLOSE 10.213.96.192:9876
2021-05-21 20:59:59,870 INFO  [NettyClientWorkerThread_1] RocketmqRemoting(Slf4jLoggerFactory.java:90) - eventCloseChannel: the channel[null] has been removed from the channel table before
2021-05-21 20:59:59,870 INFO  [eventMesh-clientmanage-2] RocketmqRemoting(Slf4jLoggerFactory.java:85) - shutdown thread NettyEventExecutor interrupt false
2021-05-21 20:59:59,870 INFO  [NettyClientSelector_1] RocketmqRemoting(Slf4jLoggerFactory.java:95) - closeChannel: close the connection to remote address[10.213.96.192:10911] result: true
2021-05-21 20:59:59,870 WARN  [NettyClientPublicExecutor_3] RocketmqClient(Slf4jLoggerFactory.java:110) - PullMessageServiceScheduledThread has shutdown
2021-05-21 20:59:59,870 WARN  [NettyClientPublicExecutor_2] RocketmqClient(Slf4jLoggerFactory.java:130) - execute the pull request exception
org.apache.rocketmq.client.exception.MQClientException: send request failed to 10.213.96.192:10911. Request: RemotingCommand [code=11, language=JAVA, version=355, opaque=278, flag(B)=0, remark=null, extFields={queueId=3, maxMsgNums=32, sysFlag=2, suspendTimeoutMillis=15000, commitOffset=0, topic=FT0-e-80010001-01-1, queueOffset=8, expressionType=TAG, subVersion=1621630675001, consumerGroup=ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0}, serializeTypeCurrentRPC=JSON]
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:752) ~[rocketmq-client-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:54) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:319) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
2021-05-21 20:59:59,870 WARN  [NettyClientPublicExecutor_3] RocketmqClient(Slf4jLoggerFactory.java:130) - execute the pull request exception
org.apache.rocketmq.client.exception.MQClientException: send request failed to 10.213.96.192:10911. Request: RemotingCommand [code=11, language=JAVA, version=355, opaque=280, flag(B)=0, remark=null, extFields={queueId=2, maxMsgNums=32, sysFlag=2, suspendTimeoutMillis=15000, commitOffset=0, topic=FT0-e-80010001-01-1, queueOffset=4, expressionType=TAG, subVersion=1621630675001, consumerGroup=ConsumerGroup-0c4433303baf4dba966a08f3f3e22949-FT0}, serializeTypeCurrentRPC=JSON]
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:752) ~[rocketmq-client-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:54) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:319) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
2021-05-21 20:59:59,870 WARN  [NettyClientPublicExecutor_2] RocketmqClient(Slf4jLoggerFactory.java:110) - PullMessageServiceScheduledThread has shutdown
2021-05-21 20:59:59,870 WARN  [NettyClientPublicExecutor_3] RocketmqClient(Slf4jLoggerFactory.java:110) - PullMessageServiceScheduledThread has shutdown
```

**Comment by jinrongluo** [comment]
From the logs, this MQClientException is coming from RocketMQ Client side.

`[NettyClientPublicExecutor_2] RocketmqClient(Slf4jLoggerFactory.java:130) - execute the pull request exception`

And it happens because thread `NettyClientPublicExecutor_2` is steill sending pull request to the broker while `PullMessageServiceScheduledThread` at the server side has shutdown.

In other words,  NettyClientPublicExecutor_2 Thread still sending the request while eventMesh-clientmanage-2 Thread is shutting down the `PullMessageService`

There need might need some coordination among the worker threads during the unsubscribe process.

**Comment by xwm1992** [comment]
> From the logs, this MQClientException is coming from RocketMQ Client side.
> 
> `[NettyClientPublicExecutor_2] RocketmqClient(Slf4jLoggerFactory.java:130) - execute the pull request exception`
> 
> And it happens because thread `NettyClientPublicExecutor_2` is steill sending pull request to the broker while `PullMessageServiceScheduledThread` at the server side has shutdown.
> 
> In other words, NettyClientPublicExecutor_2 Thread still sending the request while eventMesh-clientmanage-2 Thread is shutting down the `PullMessageService`
> 
> There might need some coordination among the worker threads during the unsubscribe process.

@jinrongluo Well, based on your description, I understand that this error is a normal phenomenon. You are unsubscribing in the consumption process, with the unsubscribe command this will close the channel between the client and broker, so client can't send any pull request to broker. So,what you are hoping for?

**Comment by jinrongluo** [comment]
Thanks @xwm1992 for clarification. I want to know this is expected behaviour. So from your reply, I think we can safely ignore this exception.
