### ISSUE TITLE
SSLContext Initialize error

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#451]
Currently, when we initialize the `EventMeshHTTPServer` it will throw an exception
```java
2021-07-21 19:53:36,923 WARN  [eventMesh-http-server] http(SSLContextFactory.java:65) - sslContext init failed
java.nio.file.NoSuchFileException: eventmesh-runtime/conf/sChat2.jks
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_275]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_275]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_275]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_275]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_275]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_275]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_275]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_275]
	at org.apache.eventmesh.runtime.boot.SSLContextFactory.getSslContext(SSLContextFactory.java:58) ~[eventmesh-runtime-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.apache.eventmesh.runtime.boot.AbstractHTTPServer.lambda$start$0(AbstractHTTPServer.java:159) ~[eventmesh-runtime-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
This caused by we delete the old `sChat2.jks` file, now if user don't set `ssl.server.cer` in env, or they don't add a `sChat2.jks` file to `confPath`, the exception will occur. It is maybe better to add a switch to control whether open SSL.

**Comment by qqeasonchen** [comment]
:( forget the ssl, update the jks file again, but it is time to add a ssl enable switch.

**Comment by lrhkobe** [comment]
As to this question, EventMesh has a ssl enable switch and the default value is false.

The user guide of HTTPS can refer to the doc in `docs/cn/features/https.zh-CN.md`  or `docs/en/features/https.md`

**Comment by ruanwenjun** [comment]
@lrhkobe Yes, I got you. We may need to refactor this code.
The switch might should be moved to `SSLContextFactory` or `AbrstractHTTPServer`, otherwise, though we set the ssl switch false, it still throws an exception(Although this does not affect application).

**Comment by lrhkobe** [comment]
@ruanwenjun I have not got you. Because I see the code which the switch is already in `AbrstractHTTPServer.java`.
```
public abstract class AbrstractHTTPServer extends AbstractRemotingServer {

    ...

    private boolean useTLS;
```

**Comment by ruanwenjun** [comment]
@ruanwenjun Yes, you are right.
When the `AbrstractHTTPServer.java` start, it will new a `HttpsServerInitializer` and execute `SSLContextFactory.getSslContext()` to inject the `SSLContext `. The problem is in the `getSslContext` doesn't judge the ssl open.

![image](https://user-images.githubusercontent.com/22415594/126601820-25f24c93-db78-48b2-ba18-a00e277b4ba4.png)

It might be better to change the code to below:
```java
SSLContext sslContext = useTLS ? SSLContextFactory.getSslContext() : null;
b.group(this.bossGroup, this.workerGroup)
        .channel(NioServerSocketChannel.class)
        .childHandler(new HttpsServerInitializer(sslContext)).childOption(ChannelOption.SO_KEEPALIVE, Boolean.TRUE);
```
